### ISSUE TITLE
Compiling on Arduino 1.8.2: <vector> is missing

### ISSUE THREAD

**Issue by moette** [bartoszbielawski/LEDMatrixDriver#1]
If you just install the library and try to compile a sketch with noting more than 

_#include "LEDMatrixDriver.hpp"_

the compile will fail with 

**LEDMatrixDriver.hpp:22:18: fatal error: vector: No such file or directory**

The library should depend on the STL or something. (Or have a hint in the read me ;))

**Comment by bartoszbielawski** [comment]
@moette Can you tell me on which platform? I will have to check which platforms have what...

**Comment by moette** [comment]
Current Arduino 1.8.2.
There is an arduinoSTL library available. This one contains a vector as well. But uses up a lot of RAM.

**Comment by bartoszbielawski** [comment]
Dependency on std::vector removed.
