### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by iZhangHui** [bartoszbielawski/LEDMatrixDriver#39]
https://github.com/bartoszbielawski/LEDMatrixDriver/blob/171afdfcb39f07e11d961de7d7e63618c5e9ad28/examples/AFGFXMarquee/AFGFXMarquee.ino#L19
---> USE_ADAF**R**UIT_GFX

**Comment by bartoszbielawski** [comment]
Thanks, I will fix it soon.

**Comment by bartoszbielawski** [comment]
Fixed in the latest commit.
