### ISSUE TITLE
SPI.setHwCs() does not exist on Arduino 1.8.2

### ISSUE THREAD

**Issue by moette** [bartoszbielawski/LEDMatrixDriver#4]
Looks like the code in here was made for ESP8266 or something?

**Comment by bartoszbielawski** [comment]
Yes, it was made for ESP8266. I had no idea they diverged so far from the standard API. Anyway - I will just use couple of #ifdefs - transferXX() are available this one can be removed, vector can be replaced with raw pointers. Or I will just mark the specific platform.

**Comment by moette** [comment]
drop me a mail at marko at oette dot info

I can supply a working version of the library and an arduino example sketch. 

Besides the above mentioned problems it works like a charm ;)

**Comment by bartoszbielawski** [comment]
Fixed in the latest commit.
