### ISSUE TITLE
Error between Software serial or Serial and setIntensivity

### ISSUE THREAD

**Issue by Adam3073** [bartoszbielawski/LEDMatrixDriver#45]
Ive got a little problem. When I run setIntenivity() methode I saw a problem with reading data from serial/ software serial port.  There are some conflict. Some time work, som time dosent.

Mam problem z użyciem metody setIntensivity. Podczas wywołania metody następuje błąd w porcie szeregowym, przez co nie mogę odbierać danych. Po wywołaniu jej port raz odbierze poprawnie, a raz odbierze dane po 10 próbach.

**Comment by bartoszbielawski** [comment]
Polish language warning!

Cześć, 

Metoda setIntensity jest zaimplementowana za pomocą metody _sendCommand() w ten sposób:
`_sendCommand(SCAN_LIMIT | limit);`

A `_sendCommand()` jest używana w wielu innych miejscach. Sugeruję sprawdzić wpierw czy inne metody takie jak:

- `setDecode()`,
- `setScanLimit()`,
- `setEnabled()`

powodują ten sam problem. To musi być jakaś interakcja między kodem SPI a kodem do UARTa.

Pozdrawiam,
Bartosz
