### ISSUE TITLE
Change Orientation

### ISSUE THREAD

**Issue by tatnka** [bartoszbielawski/LEDMatrixDriver#50]
Hi

is it possible to turn the chars by 90 degrees?
And is it possible to invert the direction the scrolling running.

(sorry for my bad english...)

Tatnka

**Comment by mikeh32217** [comment]
There is no provision for turning characters by 90 degrees.

In the code the method

void LEDMatrixDriver::scroll(scrollDirection direction, bool wrap)

allow the characters to scroll in either direction.

**Comment by bartoszbielawski** [comment]
The display doesn't care about chars, if you rotate them 90 degrees that's how it will be displayed. 
Do you want to use your display vertically?
As commented before you can change scrolling direction by providing arguments to the scroll method.

**Comment by tatnka** [comment]
thanks for the replies.
I've 4 individual 8x8 matrix elements and due to the connection pins I can only assemble them side by side. That's why I need to rotate them in software.

**Comment by tatnka** [comment]
I got it running using an additional lib. Thanks for your help!
